add reduceCopy solution
mate-academy/js_array-method-reduce pull request #1494
Opened 2023-05-09 14:35 UTC by DidenkoDenis306

2023-05-09 18:56 UTC, ghost requested changes

2023-05-09 18:56 UTC, ruslanpashkov commented on src/arrayMethodReduce.js
> +    let acc = arguments.length > 1 ? initialValue : this[0];
let's make our variables clearer and call it `accumulator` instead of `acc`

2023-05-09 18:56 UTC, ruslanpashkov commented on src/arrayMethodReduce.js
> +    const start = arguments.length > 1 ? 0 : 1;
do we need such complicated checks? we make the same thing in one `if` statement

2023-05-10 16:22 UTC, dinaminahi requested changes

2023-05-10 16:22 UTC, dinaminahi commented on src/arrayMethodReduce.js
> +    let start = 0;
Can we come up with more descriptive name here? something like `startIndex`

2023-05-12 08:14 UTC, Anna-Tkachenko approved these changes
⭐️

2024-07-09 10:17 UTC, closed without merging