solution
mate-academy/js_array-method-reduce pull request #319
Opened 2021-02-19 18:56 UTC by AnnaHarshyna

2021-02-19 19:00 UTC, yurasokal approved these changes

2021-02-22 08:54 UTC, solaryasha requested changes

2021-02-22 08:54 UTC, solaryasha commented on src/arrayMethodReduce.js
> +    if (!(typeof callback === 'function')) {
```suggestion
    if (typeof callback !== 'function') {
```

2021-02-22 08:54 UTC, solaryasha commented on src/arrayMethodReduce.js
> +      return undefined;
А ще краще викидати помилку і зупинити виконання коду
```suggestion
      return ;
```

2021-02-22 08:54 UTC, solaryasha commented on src/arrayMethodReduce.js
> +    if (typeof initialValue === 'undefined') {
Я можу явно передати в якості `initialValue` undefined і він стане акумулятором.
<img width="630" alt="Screenshot 2021-02-22 at 10 49 11" src="https://user-images.githubusercontent.com/32794096/108684973-3bdf4280-74fc-11eb-82b8-ad6f702afdff.png">

2021-02-22 12:26 UTC, solaryasha approved these changes

2023-08-07 20:19 UTC, closed without merging