solution
mate-academy/js_array-method-reduce pull request #491
Opened 2021-08-13 14:22 UTC by derelicttt

2021-08-13 14:36 UTC, sasha-morozov approved these changes
Good job!

2021-08-16 06:19 UTC, VinnieJ-2k20 requested changes
Almost done, just fix one important thing.

2021-08-16 06:19 UTC, VinnieJ-2k20 commented on src/arrayMethodReduce.js
> +    if (arguments.length < 2) {
Let's use more obvious check here.
```suggestion
    if (initialValue === undefined) {
```

2021-08-16 06:47 UTC, VinnieJ-2k20 approved these changes
Good job 👍

2022-03-03 17:55 UTC, closed without merging